### ISSUE TITLE
Validaciones en asignación de usuario

### ISSUE THREAD

**Issue by KelvinMR1997** [hguzman/NativApps#128]
-Añadir mensaje de error para los siguientes casos; cuando solo se selecciona el usuario, cuando no se selecciona ninguno
-Corregir el error: Cuando un usuario tiene 2 o más equipos, si se elimina una sola asignación se eliminan todas a causa de la regla del query.

**Comment by MERZIOX** [comment]
- Ahora el alert de validación también muestra el serial del cual se eliminara la relación.
- Ya no borra todas las relaciones asignadas a una cédula

**Comment by KelvinMR1997** [comment]
-Correjidos los bugs en los que se podian enviar datos en blanco en el select.
-Ahora el botón asignar estará inhabilitado hasta que se seleccionen ambos campos (Un usuario y un equipo.)
