### ISSUE TITLE
Errores y recomendaciones para Tickets

### ISSUE THREAD

**Issue by KelvinMR1997** [hguzman/NativApps#156]
-Incorporar una alerta cuando se envía el ticket y mostrar los detalles del mismo (Id del ticket creado, asunto , mensaje y si es posible la fecha de envío). 
POSDATA: No me sirve la creación de tickets solo recarga la pagina y ya , no se envía nada.
-Al resolver un ticket como administrador este debe cerrarse y pasar a un historial de tickets resueltos.(o simplemente puede cambiar su estado a "Resuelto" y mostrarse inmediatamente debajo de los tickets no resuelto, con la opción de eliminarlos para evitar congestión)
-Recomendación: hacer que los campos "Nombre y correo" se llenen automáticamente con el nombre y correo del usuario.
-Incorporar alerta de ticket editado en en el apartado mostrar tickets admin, antes de redirigir.
-Corregir las mayúsculas iniciales en ambos formularios tanto el de creación de ticket por parte del usuario como en edición de tickets por parte del administrador
-Corregir el responsive de la pagina; la pagina se ve mal en pantallas comunes (Resolución 1366x720px) debido a que la pantalla de nuestro compañero es más grande.

**Comment by Dimiorz** [comment]
- Se corrigió el bug en que al momento de cambiar de vista se cerraba la sesión
- Ahora el listado de los tickets se organizan según su estado, organizándose de primero los tickets pendiente y enviando al fondo los pendientes
- se añadio un campo en el que se muestra la fecha y hora de envio de los tickets

**Comment by Dimiorz** [comment]
- en la vista user - crear ticket, los campos de cedula,nombre y correo, se llenan automaticamente
- En la vista de admin - responderticket la vista general y responsive fueron corregidas
- se implementarion las plantillas modelos del header y sidebar para reducir codigo

**Comment by KelvinMR1997** [comment]
- El responsive y visualización de la pagina de tickets en 1366x720p sigue mal.

**Comment by Dimiorz** [comment]
- Error de vista responsive corregido
- La tarea de implementar las alertas fue delegada a kelvin
