### ISSUE TITLE
Auto-eliminación de tickets resueltos

### ISSUE THREAD

**Issue by KelvinMR1997** [hguzman/NativApps#185]
- Asimismo debe hacerse un archivo de tickets eliminados , una especia de historial de tickets

Esto se hace con el propósito de descongestionar la vista de tickets por parte y parte, sin embargo los tickets eliminados de dicha vista deben ser almacenados en un archivo para su posterior consulta en cualquier caso que se requiera.

**Comment by Dimiorz** [comment]
- se creo una nueva vista llamada historial de tickets, la cual permite al admin apreciar todos los tickets resueltos, y dado el caso de necesitar reabrirlos puede hacerlo tambien mediante esta vista.
- añadido al sidebar de admin acceso la nueva vista.
