### ISSUE TITLE
BUG: SOPIEC- LOGIN

### ISSUE THREAD

**Issue by Dimiorz** [hguzman/NativApps#35]
se debe autentificar el ingreso a usuario del login ,  puesto a que al redireccionar manualmente el ingreso a la dashboard no valida el ingreso de usuarios

**Comment by MERZIOX** [comment]
se a solucionado el error.

**Comment by Dimiorz** [comment]
falla no solucionada

**Comment by Dimiorz** [comment]
falla solucionada
