### ISSUE TITLE
desplegar software en produccion en hosting gratuito

### ISSUE THREAD

**Issue by Dimiorz** [hguzman/NativApps#53]
se debe desplegar el software en un hosting gratuito,  se recomienda el uso de heroku para futura implementacion

**Comment by KelvinMR1997** [comment]
Hagamos esto antes de finalizar esta semana, hay que pulir ciertos aspectos antes

**Comment by Dimiorz** [comment]
la pagina fue subida con el fork de mario para pruebas, se esta trabajando en integrar la base de datos
