### ISSUE TITLE
SOPIEC- CRUD usuarios: buscar 

### ISSUE THREAD

**Issue by Dimiorz** [hguzman/NativApps#54]
para el crud de equipos se requiere que se implemente la funcion buscar, en el cual por medio de laprimary key realte un usuario

**Comment by KelvinMR1997** [comment]
Funcion agregada, los criterios de busqueda pueden ser Cedula, Apellido, Nombre o correo

**Comment by Dimiorz** [comment]
issue no implementado en produccion
