### ISSUE TITLE
Problemas con las alertas de agregar, modificar de equipos y usuarios.

### ISSUE THREAD

**Issue by MERZIOX** [hguzman/NativApps#60]
Debido al retiro del método de php llamado session_unset() ahora las alertas quedan activas aún sin haber hecho una modificación sobre las mismas, y al estar unidas todas las alertas por la misma variable de session permanecen activas hasta cerrarlas manualmente o cerrar sesión.

**Comment by KelvinMR1997** [comment]
Corregí parcialmente el error, solo me falta añadirle un par de alertas al actualizar y añadir user , teniendo en cuenta los criterios de validación. Falta poco!

**Comment by KelvinMR1997** [comment]
#Alertas añadidas.
Las alertas estan funcionando perfectamente en las vistas de añadir usuario, editar usuario y eliminar usuario.
