### ISSUE TITLE
SOPIEC: LANDING PAGE- REDES SOCIALES

### ISSUE THREAD

**Issue by Dimiorz** [hguzman/NativApps#74]
se deben crear las respectivas redes sociales de la empresa, las cuales deben estar realcionadas a la empresa DVelEasy
Se deben crear las siguientes redes :
-faceboook
-instagram
-twitter
-pinterest(esta puede ser reemplazada por linkedin)

**Comment by MERZIOX** [comment]
## Redes sociales:
[Pagina de Facebook ](https://www.facebook.com/DVLeasy-119472056341523)
[Twitter](https://twitter.com/DvLeasy)
[Pinterest](https://co.pinterest.com/developmenteasy/)
[Instagram](https://www.instagram.com/dvleasy/)
