### ISSUE TITLE
Vista: "Ver mi usuario registrado"

### ISSUE THREAD

**Issue by MERZIOX** [hguzman/NativApps#81]
Recuperar los datos del usuario de la sesión actual y mostrarlos solamente como texto, no permitir que lo edite el usuario.
Mostrar todos los datos ingresados:
- Cédula.
- Nombre.
- Segundo nombre (opcional).
- Apellidos.
- Área.
- Correo.
- Rol.
- ID del equipo asignado (**a futuro**).

**Comment by KelvinMR1997** [comment]
![image](https://user-images.githubusercontent.com/57110967/90226663-eb628c00-ddd8-11ea-82cf-192de0b482a3.png)

Vista de admin usuario añadido

**Comment by dayadearco** [comment]
Se a resuelto el problema.
